security:
  client:
    id: ${SECURITY_CLIENT_ID:api-gateway-service}
    secret: ${SECURITY_CLIENT_SECRET:**********}
  grant-type: ${SECURITY_GRANT_TYPE:password}
  token-uri: ${SECURITY_TOKEN_URI:http://localhost:9080/realms/javaguru/protocol/openid-connect/token}
  issuer-uri: ${SECURITY_ISSUER_URI:http://localhost:9080/realms/javaguru}
  jwks-uri: ${SECURITY_JWKS_URI:http://localhost:9080/realms/javaguru/protocol/openid-connect/certs}
